# coding: utf-8

"""
    Stayforge API

    This is a basic API description.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.webhooks_manager_api import WebhooksManagerApi


class TestWebhooksManagerApi(unittest.TestCase):
    """WebhooksManagerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksManagerApi()

    def tearDown(self) -> None:
        pass

    def test_create_webhooks_profile_api_webhooks_manager_post(self) -> None:
        """Test case for create_webhooks_profile_api_webhooks_manager_post

        Create Webhooks Profile
        """
        pass

    def test_delete_webhooks_profile_api_webhooks_manager_id_delete(self) -> None:
        """Test case for delete_webhooks_profile_api_webhooks_manager_id_delete

        Delete Webhooks Profile
        """
        pass

    def test_get_webhooks_profile_api_webhooks_manager_get(self) -> None:
        """Test case for get_webhooks_profile_api_webhooks_manager_get

        Get Webhooks Profile
        """
        pass

    def test_get_webhooks_profile_api_webhooks_manager_id_get(self) -> None:
        """Test case for get_webhooks_profile_api_webhooks_manager_id_get

        Get Webhooks Profile
        """
        pass

    def test_put_webhooks_profile_api_webhooks_manager_id_put(self) -> None:
        """Test case for put_webhooks_profile_api_webhooks_manager_id_put

        Put Webhooks Profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
