# coding: utf-8

"""
    Stayforge API

    This is a basic API description.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.guest import Guest

class TestGuest(unittest.TestCase):
    """Guest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Guest:
        """Test Guest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Guest`
        """
        model = Guest()
        if include_optional:
            return Guest(
                first_name = '',
                middle_name = '',
                last_name = '',
                gender = '',
                birthday = '',
                nationality = '',
                email = '',
                phone_number = '',
                address = '',
                occupation = '',
                passport_number = '',
                id_document = openapi_client.models.id_document.IDDocument(
                    mrz = '', 
                    photocopy = null, )
            )
        else:
            return Guest(
                id_document = openapi_client.models.id_document.IDDocument(
                    mrz = '', 
                    photocopy = null, ),
        )
        """

    def testGuest(self):
        """Test Guest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
