# coding: utf-8

"""
    Stayforge API

    ![Commit Activity](https://img.shields.io/github/commit-activity/m/tokujun-t/stayforge) ![Codecov](https://codecov.io/gh/tokujun-t/stayforge/branch/main/graph/badge.svg) ![PyPI Version](https://img.shields.io/pypi/v/stayforge) ![PyPI Downloads](https://img.shields.io/pypi/dm/stayforge) ![GitHub Workflow Status](https://github.com/tokujun-t/Stayforge/actions/workflows/python-sdk.yml/badge.svg) 

    The version of the OpenAPI document: 1.0.0
    Contact: support@stayforge.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from apis.webhooks_manager_api import WebhooksManagerApi


class TestWebhooksManagerApi(unittest.TestCase):
    """WebhooksManagerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksManagerApi()

    def tearDown(self) -> None:
        pass

    def test_create_webhooks_profile_api_webhooks_manager_post(self) -> None:
        """Test case for create_webhooks_profile_api_webhooks_manager_post

        Create Webhooks Profile
        """
        pass

    def test_delete_webhooks_profile_api_webhooks_manager_id_delete(self) -> None:
        """Test case for delete_webhooks_profile_api_webhooks_manager_id_delete

        Delete Webhooks Profile
        """
        pass

    def test_get_webhooks_profile_api_webhooks_manager_get(self) -> None:
        """Test case for get_webhooks_profile_api_webhooks_manager_get

        Get Webhooks Profile
        """
        pass

    def test_get_webhooks_profile_api_webhooks_manager_id_get(self) -> None:
        """Test case for get_webhooks_profile_api_webhooks_manager_id_get

        Get Webhooks Profile
        """
        pass

    def test_put_webhooks_profile_api_webhooks_manager_id_put(self) -> None:
        """Test case for put_webhooks_profile_api_webhooks_manager_id_put

        Put Webhooks Profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
