# coding: utf-8

"""
    Stayforge API

    This is a basic API description.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.healthcheck_api import HealthcheckApi


class TestHealthcheckApi(unittest.TestCase):
    """HealthcheckApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthcheckApi()

    def tearDown(self) -> None:
        pass

    def test_info_api_healthcheck_info_get(self) -> None:
        """Test case for info_api_healthcheck_info_get

        Info
        """
        pass

    def test_ping_api_healthcheck_get(self) -> None:
        """Test case for ping_api_healthcheck_get

        Ping
        """
        pass


if __name__ == '__main__':
    unittest.main()
