# coding: utf-8

# flake8: noqa
"""
    Stayforge API

    This is a basic API description.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.api_branch_models_key import ApiBranchModelsKey
from openapi_client.models.api_branch_models_key_input import ApiBranchModelsKeyInput
from openapi_client.models.api_branch_view_key_responses import ApiBranchViewKeyResponses
from openapi_client.models.api_key_manager_models_key import ApiKeyManagerModelsKey
from openapi_client.models.api_key_manager_models_key_input import ApiKeyManagerModelsKeyInput
from openapi_client.models.api_key_manager_view_key_responses import ApiKeyManagerViewKeyResponses
from openapi_client.models.guest import Guest
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.id_document import IDDocument
from openapi_client.models.order import Order
from openapi_client.models.order_input import OrderInput
from openapi_client.models.order_responses import OrderResponses
from openapi_client.models.photocopy import Photocopy
from openapi_client.models.price import Price
from openapi_client.models.price_max import PriceMax
from openapi_client.models.price_min import PriceMin
from openapi_client.models.room import Room
from openapi_client.models.room_input import RoomInput
from openapi_client.models.room_responses import RoomResponses
from openapi_client.models.room_type import RoomType
from openapi_client.models.room_type_input import RoomTypeInput
from openapi_client.models.room_type_responses import RoomTypeResponses
from openapi_client.models.stayforge import Stayforge
from openapi_client.models.validation_error import ValidationError
from openapi_client.models.validation_error_loc_inner import ValidationErrorLocInner
from openapi_client.models.webhooks_manager import WebhooksManager
from openapi_client.models.webhooks_manager_input import WebhooksManagerInput
from openapi_client.models.webhooks_manager_responses import WebhooksManagerResponses
