# coding: utf-8

"""
    Stayforge API

    ![Commit Activity](https://img.shields.io/github/commit-activity/m/tokujun-t/stayforge) ![Codecov](https://codecov.io/gh/tokujun-t/stayforge/branch/main/graph/badge.svg) ![PyPI Version](https://img.shields.io/pypi/v/stayforge)  ### SDK  - [Python SDK](https://github.com/tokujun-t/stayforge-python)  We provided SDKs (currently only the Python version is provided). Before deciding to call the API directly, you may wish to try the SDK to speed up your development.  ![GitHub Workflow Status](https://github.com/tokujun-t/Stayforge/actions/workflows/python-sdk.yml/badge.svg)   ### About Healthcheck  Healthcheck at `/api/healthcheck`. curl to check if the service is working.  ```shell curl -I http://<your service>/api/healthcheck ``` ### Some Links  GitHub Repo [https://github.com/tokujun-t/Stayforge](https://github.com/tokujun-t/Stayforge)  Wiki [https://github.com/tokujun-t/Stayforge/wiki](https://github.com/tokujun-t/Stayforge/wiki) 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stayforge.api.message_queue_api import MessageQueueApi


class TestMessageQueueApi(unittest.TestCase):
    """MessageQueueApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessageQueueApi()

    def tearDown(self) -> None:
        pass

    def test_dequeue_api_mq_stream_get(self) -> None:
        """Test case for dequeue_api_mq_stream_get

        Dequeue
        """
        pass

    def test_enqueue_api_mq_stream_post(self) -> None:
        """Test case for enqueue_api_mq_stream_post

        Enqueue
        """
        pass

    def test_messages_api_mq_messages_stream_get(self) -> None:
        """Test case for messages_api_mq_messages_stream_get

        Messages
        """
        pass

    def test_sized_api_mq_sized_stream_get(self) -> None:
        """Test case for sized_api_mq_sized_stream_get

        Sized
        """
        pass

    def test_streams_api_mq_streams_get(self) -> None:
        """Test case for streams_api_mq_streams_get

        Streams
        """
        pass


if __name__ == '__main__':
    unittest.main()
