# coding: utf-8

# flake8: noqa
"""
    Stayforge API

    This is a basic API description.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from stayforge.models.api_branch_models_key import ApiBranchModelsKey
from stayforge.models.api_branch_models_key_input import ApiBranchModelsKeyInput
from stayforge.models.api_branch_view_key_responses import ApiBranchViewKeyResponses
from stayforge.models.api_key_manager_models_key import ApiKeyManagerModelsKey
from stayforge.models.api_key_manager_models_key_input import ApiKeyManagerModelsKeyInput
from stayforge.models.api_key_manager_view_key_responses import ApiKeyManagerViewKeyResponses
from stayforge.models.guest import Guest
from stayforge.models.http_validation_error import HTTPValidationError
from stayforge.models.id_document import IDDocument
from stayforge.models.order import Order
from stayforge.models.order_input import OrderInput
from stayforge.models.order_responses import OrderResponses
from stayforge.models.photocopy import Photocopy
from stayforge.models.price import Price
from stayforge.models.price_max import PriceMax
from stayforge.models.price_min import PriceMin
from stayforge.models.room import Room
from stayforge.models.room_input import RoomInput
from stayforge.models.room_responses import RoomResponses
from stayforge.models.room_type import RoomType
from stayforge.models.room_type_input import RoomTypeInput
from stayforge.models.room_type_responses import RoomTypeResponses
from stayforge.models.stayforge import Stayforge
from stayforge.models.validation_error import ValidationError
from stayforge.models.validation_error_loc_inner import ValidationErrorLocInner
from stayforge.models.webhooks_manager import WebhooksManager
from stayforge.models.webhooks_manager_input import WebhooksManagerInput
from stayforge.models.webhooks_manager_responses import WebhooksManagerResponses
